# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=10)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.Prato')),
            ],
        ),
    ]
