# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='preco',
            field=models.CharField(max_length=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='preco',
            field=models.CharField(max_length=10, verbose_name='preço'),
        ),
    ]
