# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_auto_20171126_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='imagem',
        ),
        migrations.AddField(
            model_name='imagem',
            name='url',
            field=models.CharField(default='https://imgur.com/1IMdEEA', max_length=200),
        ),
    ]
