# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_auto_20171126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
