# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_auto_20171126_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://i.imgur.com/DvZHEvX.jpg', max_length=200)),
            ],
        ),
    ]
