# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0006_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
    ]
