# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_delete_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='prato',
            name='preco',
        ),
    ]
