# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0008_auto_20171126_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oferta',
            new_name='Requisitado',
        ),
    ]
