# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0009_auto_20171126_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitado',
            name='imagem',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
