# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0010_auto_20171203_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='descricao',
        ),
        migrations.AddField(
            model_name='prato',
            name='descricao_breve',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requisitado',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
