# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0011_auto_20171203_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
