# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0013_auto_20171203_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background1',
        ),
        migrations.DeleteModel(
            name='Background2',
        ),
        migrations.DeleteModel(
            name='Background3',
        ),
    ]
